### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by clue4** [sandboxnu/vocab-buddy#110]
**Problem**: A lot of dependencies are deprecated (and there are a bunch of vulnerabilities)
**Solution**: fix dependencies and vulnerabilities as best you can
**Description**: there are vulnerabilities in both frontend and uploadscript folders. The amount of vulnerabilities and the number of dependencies you have may depend on your node/npm versions, so I recommend having the latest stable version.

**Specs**: 
- [ ] dependencies
- [x] vulnerabilities
- [x] get rid of yarn.lock and only use npm

**Comment by dillydally414** [comment]
cancelling this due to fear of introducing other bugs + other higher priority items
